[build]
  publish = "dist" # Update this to your build directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/"  # Match all requests to /api/*
  to = "https://mailandesha.onrender.com/:splat"  # Proxy to your backend service
  status = 200  # Keep the original status code